//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blogSitesi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Makale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Makale()
        {
            this.Yorums = new HashSet<Yorum>();
            this.Etikets = new HashSet<Etiket>();
        }
    
        public int makaleId { get; set; }
        [DisplayName("Baþlýk")]
        public string makaleBaslik { get; set; }
        [DisplayName("Ýçerik")]
        [UIHint("tinymce_full_compressed"),AllowHtml]
        public string makaleIcerik { get; set; }
        [DisplayName("Fotoðraf")]
        public string makaleFoto { get; set; }
        [DisplayName("Tarih")]
        public Nullable<System.DateTime> makaleTarih { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public Nullable<int> UyeId { get; set; }
        [DisplayName("Okunma Sayýsý")]
        public int makaleOkunma { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Uye Uye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etiket> Etikets { get; set; }
    }
}
