//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blogSitesi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Yorum
    {
        public int yorumId { get; set; }
        [DisplayName("Ýçerik")]
        public string yorumIcerik { get; set; }
        public Nullable<int> UyeId { get; set; }
        public Nullable<int> MakaleId { get; set; }
        [DisplayName("Tarih")]
        public Nullable<System.DateTime> yorumTarih { get; set; }
    
        public virtual Makale Makale { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
